### PR TITLE
Dutch translation improvements

### PR DESCRIPTION
**Pull request by btj**

### CODE REVIEW

**Comment by daveagp** [comment]
Sorry for the ridiculous delay. A server migration in the works in March finally completed. I've now pushed these changes to the server. Thank you!

Additionally, I will need to give you new editor access if you are still interested in translating content on the main site pages. Please email me if you are continuing in that role.

Cheers,
- Dave

**Comment by wp-bwinf** [comment]
Hi Dave,

we are still actively using and promoting the German (/de) version of CS Circles.  Thanks so much for setting up this course years ago and for still taking care!

Yes, we would still like to be able to translate content.  Recently, we partially lost track of how to modify some things.  For instance, there is the introductory „new around here“ sentence below the title of chapter 0 - the German translation contains a mistake, but we do not know any more where and how to edit that.  Also, our address changed more than three years ago, but we do not remember how to edit the translation of the footer.

So any hints on these are welcome, and we would definitely like to have editor access.

Thanks!
Wolfgang 


PS:  As soon as this is settled, can we get rid of the yellow insert „This site was recently migrated. …“ again?



> Am 24.11.2019 um 19:37 schrieb Dave Pritchard <notifications@github.com>:
> 
> Sorry for the ridiculous delay. A server migration in the works in March finally completed. I've now pushed these changes to the server. Thank you!
> 
> Additionally, I will need to give you new editor access if you are still interested in translating content on the main site pages. Please email me if you are continuing in that role.
> 
> Cheers,
> 
> 	• Dave
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
BWINF / Bundesweite Informatikwettbewerbe            Dr. Wolfgang Pohl
Reuterstr. 159, 53113 Bonn, GERMANY                    Geschäftsführer
Tel.: +49 228 372900-0, Fax: -1                   Tel.: +49 228 378646
bwinf@bwinf.de, www.bwinf.de                             pohl@bwinf.de

**Comment by daveagp** [comment]
Sorry for the inconvenience. We just did a server migration, and the way we used to configure editor access is from a plugin that no longer is supported.

So I am going to give you general editor access, this used to not be given just to avoid someone accidentally breaking the English pages. I suspect that's not likely to happen anyway but if you run into any problems let me know.

It looks like the bwinf user already has access - can you remind me which other user ids need it?

I expect to take off the warning in the next week or so.

**Comment by wp-bwinf** [comment]
Hello,

the bwinf user is fine, nothing else needed.  We are well able to edit the WordPress pages with this user.  

Finally, I found the German translation file in the pybox plugin. I updated the .po file and created a pull request. But I am afraid, in order to make it work, also the .mo file needs to be updated. I will try to find out how this can be done.

**Comment by wp-bwinf** [comment]
An updated .mo file has been committed as well.

**Pull request merged**
