### PR TITLE
Dutch translation of lesson files up to 10

### PR DESCRIPTION
**Pull request by joostrijneveld**
This pull request contains several lesson files translated to Dutch. We've only gone through the brief things up to lesson 10 so far, as we're using the material for a course at the moment and do not want to create any inconsistencies in the later lessons (as the Wordpress content would need more serious adjustments there). We will most likely add the rest of the translations in a separate pull request in a few months.

### CODE REVIEW

**Comment by daveagp** [comment]
Thanks for submitting it this way! Let me put in on the dev server and get back to you.

**Comment by daveagp** [comment]
Try going to http://cscircles.cemc.uwaterloo.ca/dev/1-variables-nl/ and click around to see if things look as expected. (Note that for some reason you can't go to http://cscircles.cemc.uwaterloo.ca/0-nl/, it will redirect to the non-dev site.) If it looks fine, ping back here and I'll pull to the main site.

**Comment by joostrijneveld** [comment]
Thanks! It appears to work fine; once it's on the main site, I'll gradually go through the content again, replacing the references to lesson files with their translated counterparts and fixing the surrounding texts simultaneously.

**Comment by daveagp** [comment]
Awesome! I've just added it to the real site.

**Comment by joostrijneveld** [comment]
Nice!

**Pull request merged**
